### ISSUE TITLE
Static IP

### ISSUE THREAD

**Issue by janseta** [feelfreelinux/octo4a#122]
Hi, I need to put my Octo4a as a "Static IP".

I'm able to log wth SSH, but not as root...
What must be done?

**Comment by alufers** [comment]
Hi! There are two ways you can achieve a static IP for your phone.

1. Set up a static DHCP lease on your router. (This is a better solution, because there is no chance of conflict with another device).
2. Set a static IP in the Android settings. You can follow this tutorial: https://service.uoregon.edu/TDClient/2030/Portal/KB/ArticleDet?ID=33742

Closing this, since it is not an issue with octo4a. Feel free to reach out if you need any more help.
