### ISSUE TITLE
Inclusion in default F-Droid repo?

### ISSUE THREAD

**Issue by sudomain** [feelfreelinux/octo4a#286]
Hello,

Would you be opposed to having octo4a in the default F-Droid repo? I see it's already in  the "IzzyOnDroid" repo, but I personally only use the default repo (nothing against them). If you agree to have it in the default repo and the app meets the [F-Droid inclusion policy](https://f-droid.org/docs/FAQ_-_App_Developers/#how-do-i-get-my-app-included), then I don't mind submitting the merge request to `fdroiddata`.

**Comment by alufers** [comment]
Hi! Unfortunately this app includes error telemetry using [bugsnag](https://www.bugsnag.com/) which is considered an [Antifeature](https://f-droid.org/docs/Anti-Features/#Tracking) by f-droid, so they won't accept it.

Unfortunately due to the nature of this app we are enabling it by default, because it helps us debug many crazy errors coming from weird phones. This helps us diagnose errors where the user says "The printer does not connect, HELP!".
